### ISSUE TITLE
Suggestion: Sizzle-like selectors

### ISSUE THREAD

**Issue by velosipedist** [Anahkiasen/html-object#13]
Exactly copy Sizzle's CSS-compatible selector, for have possibility do this:

```php
$element->sizzle('.foo'); // return all tags in any depth with class foo
$element->sizzle('[data-custom=something]'); // filter by attributes
// etc
```

[Symfony CSS selector](https://github.com/symfony/CssSelector/blob/master/Parser/Parser.php) can be utilized  for path parsing procedure.

It seems more developer- and standards-friendly to manipulate HTML nodes structures.

**Comment by Anahkiasen** [comment]
If you want to send a PR to add this feature it would be welcome but I'm afraid all the manipulation HTML Object > DOMElements > apply CSS Selector > rebuild HTML Objects would be rather slow in terms of performances so I won't pursue this myself
