### ISSUE TITLE
[Feature] Add `addStyle`

### ISSUE THREAD

**Issue by weotch** [Anahkiasen/html-object#28]
I'd love an `addStyle` that works similar to `addClass`.  I'm open to making a PR for it if you're interested.

**Comment by Anahkiasen** [comment]
Not sure I get it, what would it do?

**Comment by weotch** [comment]
It's been awhile, but imagine I was thinking like 

```
$el->addStyle('opacity', '.5')->addStyle('background', 'red')
```

Still, I'm cool closing this since it's been so long.
